config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index', as: :authenticated_root
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create] do
      resources :comments, only: %i[new create]
      resources :likes, only: [:create]
    end
  end
  # Defines the root path route ("/")
  # root "articles#index"
  get '/image.jpg', to: 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User'

  after_save :update_comments_counter

  private

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User'

  after_save :update_like_counter

  private

  def update_like_counter
    post.increment!(:like_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :likes
  has_many :comments

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_intger: true, greater_than_or_equal_to: 0 }
  validates :like_counter, numericality: { only_intger: true, greater_than_or_equal_to: 0 }

  after_save :update_user_post_counter

  def five_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_user_post_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id

  validates :name, presence: true
  validates :posts_counter, numericality: { only_intger: true, greater_than_or_equal_to: 0 }

  def last_three_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :photo, :bio, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :photo, :bio, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = @user.posts.find(params[:post_id])
  end

  def create
    @user = current_user
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.author = @user
    return unless @comment.save

    @user = User.find(params[:user_id])
    redirect_to user_post_path(@user, @post)
    # else
    #   render :new
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @user = User.find(params[:user_id])
  end

  def create
    @user = current_user
    @post = Post.find(params[:post_id])
    @like = @post.likes.new
    @like.author = @user
    if @like.save
      @user = User.find(params[:user_id])
      redirect_to user_post_path(@user, @post)
    else
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])
  end

  def new
    @user = User.find(params[:user_id])
    @post = @user.posts.new
  end

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.new(post_params)
    @post.comments_counter = 0
    @post.like_counter = 0
    respond_to do |format|
      format.html do
        if @post.save
          redirect_to user_posts_path(@user)
        else
          render :new, locals: { post: @post }
        end
      end
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    if params[:id] == 'sign_out'
      sign_out_and_redirect
    else
      @user = User.find(params[:id])
    end
  end

  private

  def sign_out_and_redirect
    sign_out current_user
    redirect_to new_user_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @user, url: user_posts_path, method: :post, local: true, scope: :post do |form| %>
    <div class="post_form">
      <h3>Add New Post</h3>
      <div>
        <%= form.label :title %><br>
        <%= form.text_field :title, class: 'post_title' %>
        <% form.object.errors.full_messages_for(:title).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
      <br>
      <div>
        <%= form.label :text %><br>
        <%= form.text_area :text, class: 'post_text' %>
        <% form.object.errors.full_messages_for(:text).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
      <br>
      <%= form.submit "Create Post", class: "post_button" %>
    </div>
  <% end %>

app/views/posts/index.html.erb
<%= stylesheet_link_tag 'post_index' %>

<%= render "shared/userblock", user: @user %>

<div class="all-posts">
<% Post.includes(:author, :comments).where(author: @user.id).each_with_index do |post, index|%>
    <%= link_to user_post_path(user_id: @user.id, id: post.id), class:"see-post" do %>
        <div class="post-box" >
            <div>
                <span>Post #<%= index + 1 %></span>
                <span><%= post.title%></span>
            </div>
            <p><%= post.text%></p>
            <div class="post-info">
                <span>Comments: <%= post.comments_counter %></span>
                <span>Likes: <%= post.like_counter %></span>
            </div>
        </div>
    <%end%>

    <div class="comment-box">
        <% if post.comments.empty? %>
            <%= "No comments yet!"%>
         <%else%>
            <% post.comments.each do |comment| %>
                <div>
                <span><%= "#{comment.author.name}: "%></span>
                <span><%= comment.text %></span>
                </div>
            <% end %>
        <% end %>
    </div>
<%end%>
</div>

<%= link_to new_user_post_path(params[:user_id]), class: "posts-btn" do %>
    <%= "Add new Post"%>
<% end %>
<div class="pagination">
    <button type="button">Pagination</button>
</div>

app/views/posts/new.html.erb
<%= render "form", post:@post%>

app/views/posts/show.html.erb
<%= stylesheet_link_tag 'post_show' %>

<div class="post-box">
    <div class="top">
        <div class="post-details">
            <span>Post #<%= Post.where(author_id: @user.id).find_index(@post).to_i + 1 %> by <%= @user.name %></span>
        </div>
        <div class="post-stats">
            <span>Comments: <%= @post.comments_counter %>, Likes: <%= @post.like_counter %></span>
        </div>
    </div>
    
    <div class="main">
        <span><%= @post.title %></span>
        <p><%= @post.text %></p>
    </div>
    <div class="bottom">
        <%= render 'shared/like', like: @like %>
    </div>
</div>

<div class="comments-box">
    <% if Comment.where(post_id: @post).empty? %>
                <%= "No comments yet!"%>
            <%else%>
                <% Comment.where(post_id: @post).each do |comment| %>
                    <div>
                    <span><%= "#{comment.author.name}: "%></span>
                    <span><%= comment.text %></span>
                    </div>
            <% end %>
    <% end %>
</div>
<div class="add-comment">
    <h3>Add a Comment</h3>
    <%= render 'shared/comment', comment: @comment %>
</div>

app/views/shared/_comment.html.erb
<%= form_with model: [@user, @post, Comment.new], url: user_post_comments_path(User.find(params[:user_id]), @post) do |form| %>
    <div class="comment_form">
      <div>
        <%= form.label :comment %><br>
        <%= form.text_area :text, class: 'comment_input' %>
        <% form.object.errors.full_messages_for(:text).each do |message| %>
          <div class="error_message"><%= message %></div>
        <% end %>
      </div>
      <br>
      <%= form.submit 'Submit', class: 'post_button' %>
    </div>
  <% end %>

app/views/shared/_like.html.erb
<%= form_with model: [@user, @post, Like.new], url: user_post_likes_path(User.find(params[:user_id]), @post) do |form| %>
    <div class="like_form">
      <%= form.submit "Like Post", class: 'post_button' %>
    </div>
<% end %>

app/views/shared/_userblock.html.erb
<%= stylesheet_link_tag 'userblock' %>

<div class="user-block">
  <div class="photo-box">
    <img src="<%= user.photo %>" alt="user profile photo" class="photo">
  </div>
  
  <div class="details-box">
    <h1><%= user.name%></h1>
    <span>Number of posts <%= user.posts_counter%></span>
  </div>
</div>

app/views/users/index.html.erb
<%= stylesheet_link_tag 'user_index' %>

<div class="sign-out">
  <%= link_to 'Sign out',  destroy_user_session_path, method: :delete %>
</div>

<% User.all.each do |user|%>
  <%= link_to user_path(user), class: "userlink" do %>
    <%= render "shared/userblock", user: user %>
  <%end%>
<%end%>

app/views/users/show.html.erb
<%= stylesheet_link_tag 'user_show' %>

<%= render "shared/userblock", user:@user %>

<div class="bio-box">
  <span>Bio</span>
  <p><%= @user.bio %></p>
</div>

<div class="posts-box">
  <% if @user.last_three_posts.empty? %>
    <%= "#{@user.name} has no post yet!" %>
  <%else%>
    <% @user.last_three_posts.each_with_index do |post, index| %>
        <div class="post-box">
            <span>Post #<%= index + 1 %></span>
            <p><%= post.text %></p>
        </div>
    <%end%>
  <%end%>
</div>

<%= link_to user_posts_path(params[:id]), class: "posts-btn" do %>
    <%= "See all posts"%>
<% end %>